# Generated by Django 4.0.1 on 2022-01-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predresults',
            old_name='classifcation',
            new_name='classification',
        ),
    ]
